services:
  nummo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nummo
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "9464"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
